update go to 1.19, go mod tidy, go mod vendor
The code is currently not buildable on the 1.24 release branch due to some
usage of usafe.Slice, which was added in go 1.17

I am getting errors like this when building:

       vendor/golang.org/x/sys/unix/syscall_linux.go:2256:9: undefined: unsafe.Slice